// Mock data for the medical center application
const MedicalData = {
  // Patients data
  patients: [
    {
      id: 1,
      name: "Maria Silva",
      phone: "(11) 99999-1111",
      email: "maria.silva@email.com",
      city: "São Paulo",
      birthDate: "1990-05-15",
      firstExperience: "2024-01-15",
      insurance: "unimed",
      tags: ["hipertensão", "check-up anual"],
      cpf: "123.456.789-00",
      address: "Rua das Flores, 123",
      emergencyContact: "(11) 98888-1111",
    },
    {
      id: 2,
      name: "João Santos",
      phone: "(11) 99999-2222",
      email: "joao.santos@email.com",
      city: "São Paulo",
      birthDate: "1985-08-22",
      firstExperience: "2024-03-10",
      insurance: "amil",
      tags: ["dermatite", "alergia"],
      cpf: "987.654.321-00",
      address: "Av. Paulista, 456",
      emergencyContact: "(11) 97777-2222",
    },
    {
      id: 3,
      name: "Ana Costa",
      phone: "(11) 99999-3333",
      email: "ana.costa@email.com",
      city: "Guarulhos",
      birthDate: "1992-12-03",
      firstExperience: "2023-11-20",
      insurance: "particular",
      tags: ["pediatria", "vacinação"],
      cpf: "456.789.123-00",
      address: "Rua da Esperança, 789",
    },
    {
      id: 4,
      name: "Beatriz Lima",
      phone: "(11) 99999-4444",
      email: "beatriz.lima@email.com",
      city: "São Caetano",
      birthDate: "1988-04-18",
      firstExperience: "2024-02-14",
      insurance: "sulamerica",
      tags: ["fratura", "ortopedia"],
      cpf: "321.654.987-00",
      address: "Rua das Palmeiras, 321",
    },
    {
      id: 5,
      name: "Carla Mendes",
      phone: "(11) 99999-5555",
      email: "carla.mendes@email.com",
      city: "Santo André",
      birthDate: "1995-09-07",
      firstExperience: "2024-04-05",
      insurance: "bradesco",
      tags: ["cardíaco", "check-up"],
      cpf: "159.753.486-00",
      address: "Av. Industrial, 159",
    },
    {
      id: 6,
      name: "Diana Rocha",
      phone: "(11) 99999-6666",
      email: "diana.rocha@email.com",
      city: "São Paulo",
      birthDate: "1993-11-12",
      firstExperience: "2024-01-20",
      insurance: "unimed",
      tags: ["dermatologia", "manchas"],
      cpf: "753.159.486-00",
      address: "Rua dos Jardins, 753",
    },
  ],

  // Appointments data
  appointments: [
    {
      id: 1,
      patientId: 1,
      patientName: "Maria Silva",
      phone: "(11) 99999-1111",
      service: "cardiologia",
      doctor: "dr_silva",
      time: "09:00",
      status: "confirmado",
      insurance: "unimed",
      observations: "Paciente com histórico de hipertensão",
      date: "2025-01-29",
      price: 250,
      duration: 30,
    },
    {
      id: 2,
      patientId: 2,
      patientName: "João Santos",
      phone: "(11) 99999-2222",
      service: "dermatologia",
      doctor: "dr_santos",
      time: "11:00",
      status: "pendente",
      insurance: "amil",
      observations: "Primeira consulta na clínica",
      date: "2025-01-29",
      price: 200,
      duration: 30,
    },
    {
      id: 3,
      patientId: 3,
      patientName: "Ana Costa",
      phone: "(11) 99999-3333",
      service: "pediatria",
      doctor: "dr_silva",
      time: "14:00",
      status: "confirmado",
      insurance: "particular",
      observations: "Consulta de rotina",
      date: "2025-01-29",
      price: 180,
      duration: 30,
    },
    {
      id: 4,
      patientId: 4,
      patientName: "Beatriz Lima",
      phone: "(11) 99999-4444",
      service: "ortopedia",
      doctor: "dr_santos",
      time: "10:00",
      status: "confirmado",
      insurance: "sulamerica",
      observations: "Acompanhamento pós-fratura",
      date: "2025-01-30",
      price: 220,
      duration: 45,
    },
    {
      id: 5,
      patientId: 5,
      patientName: "Carla Mendes",
      phone: "(11) 99999-5555",
      service: "cardiologia",
      doctor: "dr_silva",
      time: "15:30",
      status: "pendente",
      insurance: "bradesco",
      observations: "Check-up anual",
      date: "2025-01-30",
      price: 250,
      duration: 30,
    },
    {
      id: 6,
      patientId: 6,
      patientName: "Diana Rocha",
      phone: "(11) 99999-6666",
      service: "dermatologia",
      doctor: "dr_santos",
      time: "09:30",
      status: "confirmado",
      insurance: "unimed",
      observations: "Avaliação de manchas na pele",
      date: "2025-01-28",
      price: 200,
      duration: 30,
    },
  ],

  // Doctors data
  doctors: [
    {
      id: 1,
      name: "Dr. Carlos Silva",
      specialty: "Cardiologia",
      crm: "SP-123456",
      phone: "(11) 98765-4321",
      email: "carlos.silva@medcenter.com",
      office: "Consultório 1",
      schedule: "Seg-Sex: 08:00 - 18:00",
      consultationPrice: 250,
      avatar: null,
    },
    {
      id: 2,
      name: "Dra. Ana Santos",
      specialty: "Dermatologia",
      crm: "SP-654321",
      phone: "(11) 98765-1234",
      email: "ana.santos@medcenter.com",
      office: "Consultório 2",
      schedule: "Seg-Qui: 09:00 - 17:00",
      consultationPrice: 200,
      avatar: null,
    },
  ],

  // Time slots for appointments
  timeSlots: [
    "08:00",
    "08:30",
    "09:00",
    "09:30",
    "10:00",
    "10:30",
    "11:00",
    "11:30",
    "12:00",
    "12:30",
    "13:00",
    "13:30",
    "14:00",
    "14:30",
    "15:00",
    "15:30",
    "16:00",
    "16:30",
    "17:00",
    "17:30",
    "18:00",
  ],

  // Insurance options
  insuranceOptions: [
    { value: "particular", label: "Particular" },
    { value: "unimed", label: "Unimed" },
    { value: "amil", label: "Amil" },
    { value: "sulamerica", label: "SulAmérica" },
    { value: "bradesco", label: "Bradesco Saúde" },
  ],

  // Specialties
  specialties: [
    { value: "cardiologia", label: "Cardiologia" },
    { value: "dermatologia", label: "Dermatologia" },
    { value: "pediatria", label: "Pediatria" },
    { value: "ortopedia", label: "Ortopedia" },
    { value: "clinico", label: "Clínico Geral" },
    { value: "ginecologia", label: "Ginecologia" },
  ],

  // Activity log
  activities: [
    {
      id: 1,
      action: "Nova consulta agendada",
      description: "Maria Silva - Cardiologia",
      timestamp: new Date(Date.now() - 2 * 60 * 1000),
      type: "appointment",
    },
    {
      id: 2,
      action: "Consulta confirmada",
      description: "João Santos - Dermatologia",
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      type: "appointment",
    },
    {
      id: 3,
      action: "Novo paciente cadastrado",
      description: "Ana Costa",
      timestamp: new Date(Date.now() - 10 * 60 * 1000),
      type: "patient",
    },
    {
      id: 4,
      action: "Consulta concluída",
      description: "Carlos Lima - Ortopedia",
      timestamp: new Date(Date.now() - 15 * 60 * 1000),
      type: "appointment",
    },
  ],
}

// Export for use in other files
if (typeof module !== "undefined" && module.exports) {
  module.exports = MedicalData
}
